//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace gAutomotive.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer
    {
        public long Id { get; set; }
        public string CustomerName { get; set; }
        public string CustomerTelephone { get; set; }
        public string Mark { get; set; }
        public string WIN { get; set; }
        public Nullable<System.DateTime> OrderAcceptanceDate { get; set; }
        public Nullable<System.DateTime> OrderSellDate { get; set; }
        public Nullable<decimal> OriginalPrice { get; set; }
        public Nullable<decimal> SellPrice { get; set; }
        public Nullable<decimal> Profit { get; set; }
        public string DetailCode { get; set; }
        public string DetailReplaceCode { get; set; }
        public Nullable<int> Weight_KG { get; set; }
    }
}
